module.exports = {
  ADMIN_CODE: process.env.ADMIN_CODE,

  BLOCKFROST_API_KEY: process.env.BLOCKFROST_KEY,
  BLOCKFROST_WEBHOOK_AUTH_TOKEN: process.env.BLOCKFROST_WEBHOOK_AUTH_TOKEN,

  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
}
