module.exports = {
  ADMIN_CODE: process.env.NEXT_PUBLIC_ADMIN_CODE,
  BLOCKFROST_API_KEY: process.env.NEXT_PUBLIC_BLOCKFROST_KEY,
  BLOCKFROST_WEBHOOK_AUTH_TOKEN: process.env.NEXT_PUBLIC_BLOCKFROST_WEBHOOK_AUTH_TOKEN,
}
