name: cron-test
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route
        run: |
          curl --request POST \
          --url 'https://bad-fox-e5xgwr41e-badfoxmc.vercel.app/api/test-cron'
