name: cron-test
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route
        run: |
          curl --request POST \
          --url 'https://bad-fox-mc-git-main-badfoxmc.vercel.app/api/test-cron' \
          --header 'admin_code: ${{ secrets.ADMIN_CODE }}'
